import { Student } from "@/types";

export const initialStudents: Student[] = [
  { id: 1, name: "أحمد خليل الرشيد", absenceRate: 5, status: "Present" },
  { id: 2, name: "سارة محمد العتيبي", absenceRate: 20, status: "Absent" },
  { id: 3, name: "عمر خالد الدوسري", absenceRate: 0, status: "Present" },
  { id: 4, name: "مريم عبد الله الغامدي", absenceRate: 18, status: "Late" },
  { id: 5, name: "ياسين طارق القحطاني", absenceRate: 8, status: "Present" },
  { id: 6, name: "فاطمة حسن الشهراني", absenceRate: 25, status: "Absent" },
  { id: 7, name: "زياد فهد المطيري", absenceRate: 2, status: "Present" },
  { id: 8, name: "نورة سعد السبيعي", absenceRate: 12, status: "Present" },
  { id: 9, name: "عبد العزيز سلطان الزهراني", absenceRate: 15, status: "Late" },
  { id: 10, name: "هدى يوسف الشمري", absenceRate: 0, status: "Present" },
  { id: 11, name: "خالد إبراهيم العنزي", absenceRate: 30, status: "Absent" },
  { id: 12, name: "ريم علي الحارثي", absenceRate: 4, status: "Present" },
  { id: 13, name: "فيصل ناصر القحطاني", absenceRate: 10, status: "Late" },
  { id: 14, name: "شهد بدر المالكي", absenceRate: 22, status: "Absent" },
  { id: 15, name: "حمزة وليد البقمي", absenceRate: 6, status: "Present" },
  { id: 16, name: "عائشة ماجد الشهري", absenceRate: 0, status: "Present" },
  { id: 17, name: "سعود بندر الحربي", absenceRate: 14, status: "Present" },
  { id: 18, name: "منى سليمان الخالدي", absenceRate: 19, status: "Late" },
  { id: 19, name: "بدر مشاري الدوسري", absenceRate: 3, status: "Present" },
  { id: 20, name: "دانة عادل الغامدي", absenceRate: 28, status: "Absent" },
  { id: 21, name: "تركي هاني العتيبي", absenceRate: 9, status: "Present" },
  { id: 22, name: "جود تركي الرويلي", absenceRate: 1, status: "Present" },
  { id: 23, name: "صالح عبد الرحمن السعيد", absenceRate: 16, status: "Late" },
  { id: 24, name: "لمى خالد القحطاني", absenceRate: 0, status: "Present" },
  { id: 25, name: "محمد فايز الشمراني", absenceRate: 24, status: "Absent" },
  { id: 26, name: "أميرة صلاح الزهراني", absenceRate: 7, status: "Present" },
  { id: 27, name: "نايف ثامر المطيري", absenceRate: 11, status: "Present" },
  { id: 28, name: "ريناد سامي الحازمي", absenceRate: 13, status: "Late" },
  { id: 29, name: "وليد نواف العسيري", absenceRate: 2, status: "Present" },
  { id: 30, name: "سارة عبد العزيز الغامدي", absenceRate: 21, status: "Absent" },
];